import re

# Read the file
with open('ChatGamesModal.jsx', 'r', encoding='utf-8') as f:
    content = f.read()

# Define the new TRIVIA_QUESTIONS array
new_array = '''const TRIVIA_QUESTIONS = [
  // Science & Thinking (40 questions)
  { q: 'What is the hardest natural substance on Earth?', options: ['Gold', 'Iron', 'Diamond', 'Platinum'], answer: 'Diamond' },
  { q: 'What is the chemical symbol for gold?', options: ['Go', 'Gd', 'Au', 'Ag'], answer: 'Au' },
  { q: 'What is the largest organ in the human body?', options: ['Heart', 'Liver', 'Skin', 'Brain'], answer: 'Skin' },
  { q: 'What gas do plants absorb during photosynthesis?', options: ['Oxygen', 'Carbon dioxide', 'Nitrogen', 'Hydrogen'], answer: 'Carbon dioxide' },
  { q: 'What is the center of an atom called?', options: ['Electron', 'Nucleus', 'Proton cloud', 'Ion'], answer: 'Nucleus' },
  { q: 'What is the speed of light in vacuum?', options: ['300,000 km/s', '150,000 km/s', '1,000,000 km/s', '30,000 km/s'], answer: '300,000 km/s' },
  { q: 'What is the powerhouse of the cell?', options: ['Nucleus', 'Ribosome', 'Mitochondria', 'Golgi body'], answer: 'Mitochondria' },
  { q: 'What is the most abundant gas in Earth\'s atmosphere?', options: ['Oxygen', 'Carbon dioxide', 'Nitrogen', 'Hydrogen'], answer: 'Nitrogen' },
  { q: 'What is the boiling point of water at sea level?', options: ['90°C', '100°C', '110°C', '120°C'], answer: '100°C' },
  { q: 'What type of energy is stored in a battery?', options: ['Kinetic', 'Potential', 'Thermal', 'Nuclear'], answer: 'Potential' },
  { q: 'What is the smallest unit of life?', options: ['Atom', 'Molecule', 'Cell', 'Tissue'], answer: 'Cell' },
  { q: 'What is the process by which plants make food?', options: ['Respiration', 'Photosynthesis', 'Digestion', 'Fermentation'], answer: 'Photosynthesis' },
  { q: 'What is the chemical formula for water?', options: ['HO', 'H2O', 'H2O2', 'CO2'], answer: 'H2O' },
  { q: 'What is the largest planet in our solar system?', options: ['Saturn', 'Jupiter', 'Neptune', 'Uranus'], answer: 'Jupiter' },
  { q: 'What is the study of fossils called?', options: ['Geology', 'Paleontology', 'Archaeology', 'Biology'], answer: 'Paleontology' },
  { q: 'What is the process of cell division called?', options: ['Mitosis', 'Meiosis', 'Osmosis', 'Diffusion'], answer: 'Mitosis' },
  { q: 'What is the unit of electrical resistance?', options: ['Volt', 'Ampere', 'Ohm', 'Watt'], answer: 'Ohm' },
  { q: 'What is the force that pulls objects toward Earth?', options: ['Magnetism', 'Friction', 'Gravity', 'Tension'], answer: 'Gravity' },
  { q: 'What is the study of insects called?', options: ['Botany', 'Zoology', 'Entomology', 'Ornithology'], answer: 'Entomology' },
  { q: 'What is the most common element in the universe?', options: ['Oxygen', 'Carbon', 'Hydrogen', 'Helium'], answer: 'Hydrogen' },
  { q: 'What is the process of liquid turning to gas called?', options: ['Freezing', 'Melting', 'Evaporation', 'Condensation'], answer: 'Evaporation' },
  { q: 'What is the study of weather called?', options: ['Geology', 'Meteorology', 'Astronomy', 'Oceanography'], answer: 'Meteorology' },
  { q: 'What is the basic unit of heredity?', options: ['Cell', 'Gene', 'Chromosome', 'DNA'], answer: 'Gene' },
  { q: 'What is the chemical symbol for oxygen?', options: ['Ox', 'O', 'Og', 'On'], answer: 'O' },
  { q: 'What is the study of the mind and behavior called?', options: ['Sociology', 'Psychology', 'Philosophy', 'Anthropology'], answer: 'Psychology' },
  { q: 'What is the process of gas turning to liquid called?', options: ['Evaporation', 'Condensation', 'Sublimation', 'Freezing'], answer: 'Condensation' },
  { q: 'What is the largest bone in the human body?', options: ['Skull', 'Femur', 'Humerus', 'Spine'], answer: 'Femur' },
  { q: 'What is the study of earthquakes called?', options: ['Geology', 'Seismology', 'Volcanology', 'Meteorology'], answer: 'Seismology' },
  { q: 'What is the chemical symbol for sodium?', options: ['So', 'Na', 'Sd', 'Nm'], answer: 'Na' },
  { q: 'What is the process by which the body breaks down food?', options: ['Circulation', 'Digestion', 'Respiration', 'Excretion'], answer: 'Digestion' },
  { q: 'What is the study of plants called?', options: ['Zoology', 'Botany', 'Biology', 'Ecology'], answer: 'Botany' },
  { q: 'What is the SI unit of force?', options: ['Joule', 'Watt', 'Newton', 'Pascal'], answer: 'Newton' },
  { q: 'What is the outer layer of Earth called?', options: ['Core', 'Mantle', 'Crust', 'Atmosphere'], answer: 'Crust' },
  { q: 'What is the process of solid turning to liquid called?', options: ['Freezing', 'Melting', 'Evaporation', 'Sublimation'], answer: 'Melting' },
  { q: 'What is the study of animals called?', options: ['Botany', 'Zoology', 'Biology', 'Ecology'], answer: 'Zoology' },
  { q: 'What is the chemical symbol for iron?', options: ['Ir', 'Fe', 'In', 'Io'], answer: 'Fe' },
  { q: 'What is the process by which organisms maintain stable internal conditions?', options: ['Evolution', 'Homeostasis', 'Metabolism', 'Reproduction'], answer: 'Homeostasis' },
  { q: 'What is the study of viruses called?', options: ['Bacteriology', 'Virology', 'Mycology', 'Parasitology'], answer: 'Virology' },
  { q: 'What is the SI unit of energy?', options: ['Newton', 'Joule', 'Watt', 'Pascal'], answer: 'Joule' },
  { q: 'What is the process of a solid turning directly to gas called?', options: ['Evaporation', 'Condensation', 'Sublimation', 'Deposition'], answer: 'Sublimation' },
  { q: 'What is the study of the structure and function of cells called?', options: ['Genetics', 'Cytology', 'Histology', 'Anatomy'], answer: 'Cytology' },

  // Islamic History - Medieval Period (30 questions)
  { q: 'In which year did the Prophet Muhammad (PBUH) receive the first revelation?', options: ['610 CE', '622 CE', '632 CE', '570 CE'], answer: '610 CE' },
  { q: 'What is the Hijra referring to in Islamic history?', options: ['The first revelation', 'The migration to Medina', 'The Battle of Badr', 'The conquest of Mecca'], answer: 'The migration to Medina' },
  { q: 'Which year marks the beginning of the Islamic calendar?', options: ['610 CE', '622 CE', '632 CE', '570 CE'], answer: '622 CE' },
  { q: 'What was the first major battle in Islamic history?', options: ['Battle of Uhud', 'Battle of Badr', 'Battle of the Trench', 'Battle of Khaybar'], answer: 'Battle of Badr' },
  { q: 'Who was the first Caliph after the Prophet Muhammad (PBUH)?', options: ['Umar ibn al-Khattab', 'Uthman ibn Affan', 'Ali ibn Abi Talib', 'Abu Bakr as-Siddiq'], answer: 'Abu Bakr as-Siddiq' },
  { q: 'Which city did the Prophet Muhammad (PBUH) migrate to during the Hijra?', options: ['Jerusalem', 'Damascus', 'Medina', 'Cairo'], answer: 'Medina' },
  { q: 'What is the name of the Prophet\'s first wife?', options: ['Aisha', 'Khadijah', 'Hafsa', 'Fatimah'], answer: 'Khadijah' },
  { q: 'Which battle is known as the Battle of the Trench?', options: ['Battle of Badr', 'Battle of Uhud', 'Battle of the Trench', 'Battle of Khandaq'], answer: 'Battle of the Trench' },
  { q: 'Who compiled the Quran into a single book during the Caliphate of Abu Bakr?', options: ['Umar ibn al-Khattab', 'Uthman ibn Affan', 'Zayd ibn Thabit', 'Ali ibn Abi Talib'], answer: 'Zayd ibn Thabit' },
  { q: 'Which Caliph ordered the standardization of the Quranic text?', options: ['Abu Bakr', 'Umar', 'Uthman', 'Ali'], answer: 'Uthman' },
  { q: 'What was the name of the Islamic state established after the Prophet\'s death?', options: ['Ottoman Empire', 'Umayyad Caliphate', 'Rashidun Caliphate', 'Abbasid Caliphate'], answer: 'Rashidun Caliphate' },
  { q: 'Which companion of the Prophet was known as "The Trusted One"?', options: ['Umar ibn al-Khattab', 'Abu Bakr as-Siddiq', 'Uthman ibn Affan', 'Ali ibn Abi Talib'], answer: 'Abu Bakr as-Siddiq' },
  { q: 'What year did the Prophet Muhammad (PBUH) pass away?', options: ['610 CE', '622 CE', '632 CE', '634 CE'], answer: '632 CE' },
  { q: 'Which battle took place in 624 CE?', options: ['Battle of Uhud', 'Battle of Badr', 'Battle of the Trench', 'Conquest of Mecca'], answer: 'Battle of Badr' },
  { q: 'Who was the Prophet\'s daughter who married Ali?', options: ['Aisha', 'Khadijah', 'Fatimah', 'Hafsa'], answer: 'Fatimah' },
  { q: 'What is the name of the cave where the Prophet received the first revelation?', options: ['Cave of Thawr', 'Cave of Hira', 'Cave of Seven Sleepers', 'Cave of Abraham'], answer: 'Cave of Hira' },
  { q: 'Which Caliph was known for his justice and was called "Al-Farooq"?', options: ['Abu Bakr', 'Umar', 'Uthman', 'Ali'], answer: 'Umar' },
  { q: 'What was the first Islamic capital city?', options: ['Mecca', 'Medina', 'Damascus', 'Baghdad'], answer: 'Medina' },
  { q: 'Who was the first person to accept Islam after Khadijah?', options: ['Ali ibn Abi Talib', 'Abu Bakr', 'Umar ibn al-Khattab', 'Zayd ibn Harithah'], answer: 'Ali ibn Abi Talib' },
  { q: 'Which battle resulted in a Muslim defeat despite numerical superiority?', options: ['Battle of Badr', 'Battle of Uhud', 'Battle of the Trench', 'Conquest of Mecca'], answer: 'Battle of Uhud' },
  { q: 'What was the Treaty of Hudaybiyyah?', options: ['A peace treaty with Mecca', 'A trade agreement', 'A military alliance', 'A marriage contract'], answer: 'A peace treaty with Mecca' },
  { q: 'Who was the Prophet\'s uncle who protected him in Mecca?', options: ['Abu Talib', 'Abu Lahab', 'Hamza', 'Abbas'], answer: 'Abu Talib' },
  { q: 'Which year did the Muslims conquer Mecca peacefully?', options: ['628 CE', '630 CE', '632 CE', '634 CE'], answer: '630 CE' },
  { q: 'What is the name of the Prophet\'s grandfather?', options: ['Abdul Muttalib', 'Abdullah', 'Hashim', 'Abu Talib'], answer: 'Abdul Muttalib' },
  { q: 'Who was the first muezzin in Islam?', options: ['Bilal ibn Rabah', 'Umar ibn al-Khattab', 'Ali ibn Abi Talib', 'Abu Bakr'], answer: 'Bilal ibn Rabah' },
  { q: 'Which Caliph was assassinated while leading prayer?', options: ['Abu Bakr', 'Umar', 'Uthman', 'Ali'], answer: 'Umar' },
  { q: 'What was the name of the Prophet\'s foster mother?', options: ['Aminah', 'Halimah as-Sa\'diyyah', 'Khadijah', 'Fatimah'], answer: 'Halimah as-Sa\'diyyah' },
  { q: 'Who was the Prophet\'s companion known for his knowledge of hadith?', options: ['Abu Hurairah', 'Umar ibn al-Khattab', 'Ali ibn Abi Talib', 'Khalid ibn al-Walid'], answer: 'Abu Hurairah' },
  { q: 'Which battle is known for the strategic use of the trench?', options: ['Battle of Badr', 'Battle of Uhud', 'Battle of the Trench', 'Battle of Khaybar'], answer: 'Battle of the Trench' },
  { q: 'What was the name of the Prophet\'s mother?', options: ['Khadijah', 'Aminah', 'Fatimah', 'Hafsa'], answer: 'Aminah' },
  { q: 'Who was the general known as "The Sword of God"?', options: ['Khalid ibn al-Walid', 'Umar ibn al-Khattab', 'Ali ibn Abi Talib', 'Hamza'], answer: 'Khalid ibn al-Walid' },

  // Computer Science & Technology (25 questions)
  { q: 'What does CPU stand for?', options: ['Central Processing Unit', 'Computer Personal Unit', 'Central Program Utility', 'Computer Processing Unit'], answer: 'Central Processing Unit' },
  { q: 'What is the purpose of RAM in a computer?', options: ['Long-term storage', 'Temporary memory', 'Processing data', 'Graphics rendering'], answer: 'Temporary memory' },
  { q: 'What does HTTP stand for?', options: ['HyperText Transfer Protocol', 'High Tech Transfer Protocol', 'HyperText Technical Protocol', 'HyperText Transmission Protocol'], answer: 'HyperText Transfer Protocol' },
  { q: 'What is an IP address?', options: ['Internet Protocol address', 'Internal Program address', 'Internet Personal address', 'Internal Protocol address'], answer: 'Internet Protocol address' },
  { q: 'What does HTML stand for?', options: ['HyperText Markup Language', 'High Tech Modern Language', 'HyperText Modern Language', 'HyperText Markup Link'], answer: 'HyperText Markup Language' },
  { q: 'What is a firewall in computing?', options: ['Hardware cooling system', 'Network security system', 'Software installer', 'File compression tool'], answer: 'Network security system' },
  { q: 'What does URL stand for?', options: ['Universal Resource Locator', 'Uniform Resource Locator', 'Universal Reference Link', 'Uniform Reference Locator'], answer: 'Uniform Resource Locator' },
  { q: 'What is the function of an operating system?', options: ['Browse internet', 'Manage computer hardware', 'Create documents', 'Play games'], answer: 'Manage computer hardware' },
  { q: 'What does Wi-Fi stand for?', options: ['Wireless Fidelity', 'Wireless Fiber', 'Wireless Frequency', 'Wireless Facility'], answer: 'Wireless Fidelity' },
  { q: 'What is a browser cache?', options: ['Storage of web files', 'Computer cooling', 'Browser security', 'Network speed'], answer: 'Storage of web files' },
  { q: 'What does VPN stand for?', options: ['Virtual Private Network', 'Virtual Public Network', 'Virtual Protocol Network', 'Virtual Protected Network'], answer: 'Virtual Private Network' },
  { q: 'What is the purpose of an algorithm?', options: ['Store data', 'Solve problems step-by-step', 'Display graphics', 'Connect to internet'], answer: 'Solve problems step-by-step' },
  { q: 'What does CSS stand for?', options: ['Computer Style Sheets', 'Cascading Style Sheets', 'Creative Style System', 'Colorful Style Sheets'], answer: 'Cascading Style Sheets' },
  { q: 'What is a database?', options: ['Collection of organized data', 'Computer program', 'Internet browser', 'Storage device'], answer: 'Collection of organized data' },
  { q: 'What does cloud computing mean?', options: ['Weather prediction', 'Storing data on internet servers', 'Computer cooling', 'Air conditioning'], answer: 'Storing data on internet servers' },
  { q: 'What is a server?', options: ['Computer that provides services', 'Food service', 'Internet browser', 'Storage device'], answer: 'Computer that provides services' },
  { q: 'What does JPEG stand for?', options: ['Joint Photographic Experts Group', 'Joint Picture Electronic Graphics', 'Joint Photo Electronic Group', 'Joint Photographic Electronic Graphics'], answer: 'Joint Photographic Experts Group' },
  { q: 'What is a computer virus?', options: ['Malicious software', 'Hardware component', 'Browser extension', 'Operating system'], answer: 'Malicious software' },
  { q: 'What does PDF stand for?', options: ['Portable Document Format', 'Personal Data File', 'Portable Data Format', 'Personal Document Format'], answer: 'Portable Document Format' },
  { q: 'What is the function of a graphics card?', options: ['Process graphics and images', 'Store documents', 'Connect to internet', 'Manage memory'], answer: 'Process graphics and images' },
  { q: 'What does USB stand for?', options: ['Universal Serial Bus', 'Universal Service Bus', 'Universal Serial Buffer', 'Universal Service Buffer'], answer: 'Universal Serial Bus' },
  { q: 'What is encryption?', options: ['Converting data into secure code', 'Deleting files', 'Compressing data', 'Backing up data'], answer: 'Converting data into secure code' },
  { q: 'What does AI stand for?', options: ['Artificial Intelligence', 'Automated Intelligence', 'Advanced Integration', 'Automated Integration'], answer: 'Artificial Intelligence' },
  { q: 'What is a search engine?', options: ['Tool to find information on web', 'Computer repair tool', 'Storage device', 'Word processor'], answer: 'Tool to find information on web' },
  { q: 'What does IoT stand for?', options: ['Internet of Things', 'Internet of Technology', 'Integration of Things', 'Internet of Tools'], answer: 'Internet of Things' },

  // India (30 questions)
  { q: 'What is the capital of India?', options: ['Mumbai', 'Delhi', 'Bangalore', 'Kolkata'], answer: 'Delhi' },
  { q: 'Who was the first Prime Minister of India?', options: ['Mahatma Gandhi', 'Jawaharlal Nehru', 'Sardar Patel', 'Subhas Chandra Bose'], answer: 'Jawaharlal Nehru' },
  { q: 'What is the national currency of India?', options: ['Dollar', 'Euro', 'Rupee', 'Yen'], answer: 'Rupee' },
  { q: 'Which river is known as the Ganges in India?', options: ['Yamuna', 'Ganga', 'Brahmaputra', 'Godavari'], answer: 'Ganga' },
  { q: 'What is the national flower of India?', options: ['Rose', 'Lotus', 'Sunflower', 'Marigold'], answer: 'Lotus' },
  { q: 'Which city is known as the Silicon Valley of India?', options: ['Mumbai', 'Bangalore', 'Hyderabad', 'Chennai'], answer: 'Bangalore' },
  { q: 'What is the national bird of India?', options: ['Peacock', 'Eagle', 'Parrot', 'Sparrow'], answer: 'Peacock' },
  { q: 'Who wrote the Indian national anthem?', options: ['Rabindranath Tagore', 'Bankim Chandra', 'Sarojini Naidu', 'Premchand'], answer: 'Rabindranath Tagore' },
  { q: 'What is the national animal of India?', options: ['Lion', 'Tiger', 'Elephant', 'Leopard'], answer: 'Tiger' },
  { q: 'Which is the longest river in India?', options: ['Yamuna', 'Ganga', 'Brahmaputra', 'Godavari'], answer: 'Ganga' },
  { q: 'What is the name of the Indian parliament?', options: ['Sansad', 'Lok Sabha', 'Rajya Sabha', 'Parliament House'], answer: 'Sansad' },
  { q: 'Which state in India is known as the "Land of Five Rivers"?', options: ['Punjab', 'Haryana', 'Uttar Pradesh', 'Rajasthan'], answer: 'Punjab' },
  { q: 'What is the national sport of India?', options: ['Cricket', 'Hockey', 'Football', 'Kabaddi'], answer: 'Hockey' },
  { q: 'Which city is known as the "City of Joy"?', options: ['Mumbai', 'Kolkata', 'Delhi', 'Chennai'], answer: 'Kolkata' },
  { q: 'What is the highest civilian award in India?', options: ['Padma Shri', 'Padma Bhushan', 'Bharat Ratna', 'Padma Vibhushan'], answer: 'Bharat Ratna' },
  { q: 'Which monument is known as the "Symbol of Love"?', options: ['Red Fort', 'Taj Mahal', 'Qutub Minar', 'India Gate'], answer: 'Taj Mahal' },
  { q: 'What is the national tree of India?', options: ['Banyan', 'Neem', 'Peepal', 'Mango'], answer: 'Banyan' },
  { q: 'Which state is known as the "Spice Garden of India"?', options: ['Punjab', 'Kerala', 'Gujarat', 'Maharashtra'], answer: 'Kerala' },
  { q: 'What is the official language of the Indian government?', options: ['Hindi', 'English', 'Both Hindi and English', 'Sanskrit'], answer: 'Both Hindi and English' },
  { q: 'Which city is known as the "Pink City"?', options: ['Jaipur', 'Udaipur', 'Jodhpur', 'Bikaner'], answer: 'Jaipur' },
  { q: 'What is the national anthem of India called?', options: ['Jana Gana Mana', 'Vande Mataram', 'Saare Jahan Se Achha', 'Maa Tujhe Salaam'], answer: 'Jana Gana Mana' },
  { q: 'Which state is known as the "Land of the Rising Sun"?', options: ['Arunachal Pradesh', 'Assam', 'Manipur', 'Nagaland'], answer: 'Arunachal Pradesh' },
  { q: 'What is the name of the Indian space agency?', options: ['ISRO', 'NASA', 'ESA', 'CNSA'], answer: 'ISRO' },
  { q: 'Which city is known as the "Financial Capital of India"?', options: ['Delhi', 'Mumbai', 'Bangalore', 'Chennai'], answer: 'Mumbai' },
  { q: 'What is the national song of India?', options: ['Jana Gana Mana', 'Vande Mataram', 'Saare Jahan Se Achha', 'Maa Tujhe Salaam'], answer: 'Vande Mataram' },
  { q: 'Which state is known as the "God\'s Own Country"?', options: ['Goa', 'Kerala', 'Tamil Nadu', 'Karnataka'], answer: 'Kerala' },
  { q: 'What is the highest mountain peak in India?', options: ['K2', 'Kangchenjunga', 'Nanda Devi', 'Mount Everest'], answer: 'Kangchenjunga' },
  { q: 'Which city is known as the "City of Lakes"?', options: ['Udaipur', 'Jaipur', 'Jodhpur', 'Bikaner'], answer: 'Udaipur' },
  { q: 'What is the national fruit of India?', options: ['Apple', 'Mango', 'Banana', 'Orange'], answer: 'Mango' },
  { q: 'Which state is known as the "Land of Kings"?', options: ['Gujarat', 'Rajasthan', 'Punjab', 'Haryana'], answer: 'Rajasthan' },

  // World Geography (25 questions)
  { q: 'What is the largest ocean on Earth?', options: ['Atlantic', 'Pacific', 'Indian', 'Arctic'], answer: 'Pacific' },
  { q: 'What is the longest river in the world?', options: ['Amazon', 'Nile', 'Yangtze', 'Mississippi'], answer: 'Nile' },
  { q: 'What is the smallest country in the world?', options: ['Monaco', 'Vatican City', 'San Marino', 'Liechtenstein'], answer: 'Vatican City' },
  { q: 'What is the largest desert in the world?', options: ['Sahara', 'Arabian', 'Gobi', 'Antarctic'], answer: 'Antarctic' },
  { q: 'What is the capital of Australia?', options: ['Sydney', 'Melbourne', 'Canberra', 'Perth'], answer: 'Canberra' },
  { q: 'What is the largest continent by area?', options: ['Africa', 'Asia', 'Europe', 'North America'], answer: 'Asia' },
  { q: 'What is the most populous country in the world?', options: ['USA', 'India', 'China', 'Indonesia'], answer: 'India' },
  { q: 'What is the capital of Japan?', options: ['Osaka', 'Kyoto', 'Tokyo', 'Yokohama'], answer: 'Tokyo' },
  { q: 'What is the longest mountain range in the world?', options: ['Himalayas', 'Andes', 'Alps', 'Rockies'], answer: 'Andes' },
  { q: 'What is the capital of Brazil?', options: ['São Paulo', 'Rio de Janeiro', 'Brasília', 'Salvador'], answer: 'Brasília' },
  { q: 'What is the largest island in the world?', options: ['Greenland', 'New Guinea', 'Borneo', 'Madagascar'], answer: 'Greenland' },
  { q: 'What is the capital of Russia?', options: ['Saint Petersburg', 'Moscow', 'Novosibirsk', 'Kazan'], answer: 'Moscow' },
  { q: 'What is the highest waterfall in the world?', options: ['Niagara Falls', 'Angel Falls', 'Victoria Falls', 'Iguazu Falls'], answer: 'Angel Falls' },
  { q: 'What is the capital of Egypt?', options: ['Alexandria', 'Cairo', 'Luxor', 'Giza'], answer: 'Cairo' },
  { q: 'What is the largest bay in the world?', options: ['Hudson Bay', 'Bay of Bengal', 'Gulf of Mexico', 'Great Australian Bight'], answer: 'Bay of Bengal' },
  { q: 'What is the capital of South Africa?', options: ['Cape Town', 'Johannesburg', 'Pretoria', 'Durban'], answer: 'Pretoria' },
  { q: 'What is the deepest lake in the world?', options: ['Caspian Sea', 'Lake Baikal', 'Lake Superior', 'Lake Victoria'], answer: 'Lake Baikal' },
  { q: 'What is the capital of Argentina?', options: ['Córdoba', 'Rosario', 'Buenos Aires', 'Mendoza'], answer: 'Buenos Aires' },
  { q: 'What is the largest coral reef system?', options: ['Great Barrier Reef', 'Belize Barrier Reef', 'Red Sea Coral Reef', 'New Caledonia Barrier Reef'], answer: 'Great Barrier Reef' },
  { q: 'What is the capital of France?', options: ['Lyon', 'Marseille', 'Paris', 'Nice'], answer: 'Paris' },
  { q: 'What is the most densely populated country?', options: ['Singapore', 'Monaco', 'Malta', 'Bahrain'], answer: 'Monaco' },
  { q: 'What is the capital of Germany?', options: ['Munich', 'Hamburg', 'Berlin', 'Frankfurt'], answer: 'Berlin' },
  { q: 'What is the largest saltwater lake?', options: ['Caspian Sea', 'Dead Sea', 'Great Salt Lake', 'Lake Van'], answer: 'Caspian Sea' },
  { q: 'What is the capital of Italy?', options: ['Milan', 'Venice', 'Rome', 'Florence'], answer: 'Rome' },
  { q: 'What is the largest river by volume?', options: ['Amazon', 'Nile', 'Yangtze', 'Mississippi'], answer: 'Amazon' },

  // World History (20 questions)
  { q: 'Who was the first President of the United States?', options: ['Thomas Jefferson', 'George Washington', 'John Adams', 'Benjamin Franklin'], answer: 'George Washington' },
  { q: 'In which year did World War II end?', options: ['1943', '1944', '1945', '1946'], answer: '1945' },
  { q: 'Who discovered America in 1492?', options: ['Vasco da Gama', 'Christopher Columbus', 'Ferdinand Magellan', 'Amerigo Vespucci'], answer: 'Christopher Columbus' },
  { q: 'What was the name of the ship that sank in 1912?', options: ['Lusitania', 'Titanic', 'Bismarck', 'Queen Mary'], answer: 'Titanic' },
  { q: 'Who built the Great Wall of China?', options: ['Mongols', 'Qin Dynasty', 'Han Dynasty', 'Ming Dynasty'], answer: 'Qin Dynasty' },
  { q: 'In which year did the French Revolution begin?', options: ['1776', '1789', '1799', '1815'], answer: '1789' },
  { q: 'Who was the first woman to fly solo across the Atlantic?', options: ['Bessie Coleman', 'Amelia Earhart', 'Harriet Quimby', 'Jacqueline Cochran'], answer: 'Amelia Earhart' },
  { q: 'What ancient civilization built the pyramids?', options: ['Romans', 'Greeks', 'Egyptians', 'Mayans'], answer: 'Egyptians' },
  { q: 'Who wrote the Declaration of Independence?', options: ['George Washington', 'Thomas Jefferson', 'Benjamin Franklin', 'John Adams'], answer: 'Thomas Jefferson' },
  { q: 'What was the Cold War between?', options: ['USA and USSR', 'USA and China', 'UK and Germany', 'France and Russia'], answer: 'USA and USSR' },
  { q: 'Who was the first Emperor of Rome?', options: ['Julius Caesar', 'Augustus', 'Nero', 'Caligula'], answer: 'Augustus' },
  { q: 'In which year did the Berlin Wall fall?', options: ['1987', '1988', '1989', '1990'], answer: '1989' },
  { q: 'Who painted the Mona Lisa?', options: ['Michelangelo', 'Leonardo da Vinci', 'Raphael', 'Donatello'], answer: 'Leonardo da Vinci' },
  { q: 'What ancient wonder was located in Alexandria?', options: ['Hanging Gardens', 'Lighthouse', 'Colossus', 'Mausoleum'], answer: 'Lighthouse' },
  { q: 'Who was the leader of the Civil Rights Movement in USA?', options: ['Malcolm X', 'Martin Luther King Jr.', 'Rosa Parks', 'Nelson Mandela'], answer: 'Martin Luther King Jr.' },
  { q: 'What empire was ruled by Genghis Khan?', options: ['Roman Empire', 'Mongol Empire', 'Ottoman Empire', 'Persian Empire'], answer: 'Mongol Empire' },
  { q: 'In which year did World War I begin?', options: ['1912', '1914', '1916', '1918'], answer: '1914' },
  { q: 'Who was the first person to reach the South Pole?', options: ['Roald Amundsen', 'Robert Falcon Scott', 'Ernest Shackleton', 'James Cook'], answer: 'Roald Amundsen' },
  { q: 'What was the capital of the Byzantine Empire?', options: ['Rome', 'Athens', 'Constantinople', 'Alexandria'], answer: 'Constantinople' },
  { q: 'Who invented the printing press?', options: ['Galileo', 'Johannes Gutenberg', 'Leonardo da Vinci', 'Isaac Newton'], answer: 'Johannes Gutenberg' },

  // Civics & Politics (20 questions)
  { q: 'What is the supreme law of the United States?', options: ['Declaration of Independence', 'Constitution', 'Bill of Rights', 'Magna Carta'], answer: 'Constitution' },
  { q: 'How many branches of government exist in the US?', options: ['2', '3', '4', '5'], answer: '3' },
  { q: 'What is the term for a country ruled by a king or queen?', options: ['Republic', 'Democracy', 'Monarchy', 'Dictatorship'], answer: 'Monarchy' },
  { q: 'What is the main duty of the judicial branch?', options: ['Make laws', 'Enforce laws', 'Interpret laws', 'Vote on laws'], answer: 'Interpret laws' },
  { q: 'What is the term for voting in an election?', options: ['Census', 'Ballot', 'Suffrage', 'Referendum'], answer: 'Suffrage' },
  { q: 'What is the upper house of the US Congress called?', options: ['House of Representatives', 'Senate', 'Supreme Court', 'Cabinet'], answer: 'Senate' },
  { q: 'What is a democracy?', options: ['Rule by one person', 'Rule by the people', 'Rule by military', 'Rule by the wealthy'], answer: 'Rule by the people' },
  { q: 'What is the term for a citizen\'s rights and responsibilities?', options: ['Privileges', 'Civics', 'Citizenship', 'Liberty'], answer: 'Citizenship' },
  { q: 'What is the length of a US presidential term?', options: ['4 years', '6 years', '8 years', '2 years'], answer: '4 years' },
  { q: 'What is the name of the first ten amendments to the US Constitution?', options: ['Articles of Confederation', 'Bill of Rights', 'Declaration of Rights', 'Constitutional Amendments'], answer: 'Bill of Rights' },
  { q: 'What is the term for a system where government controls the economy?', options: ['Capitalism', 'Socialism', 'Communism', 'Fascism'], answer: 'Communism' },
  { q: 'What is the role of the executive branch?', options: ['Make laws', 'Enforce laws', 'Interpret laws', 'Review laws'], answer: 'Enforce laws' },
  { q: 'What is the minimum age to become US President?', options: ['30', '35', '40', '45'], answer: '35' },
  { q: 'What is the legislative branch responsible for?', options: ['Enforcing laws', 'Making laws', 'Interpreting laws', 'Judging laws'], answer: 'Making laws' },
  { q: 'What is the term for government by the wealthy?', options: ['Democracy', 'Oligarchy', 'Plutocracy', 'Aristocracy'], answer: 'Plutocracy' },
  { q: 'How many justices serve on the US Supreme Court?', options: ['7', '8', '9', '10'], answer: '9' },
  { q: 'What is the vice president\'s role in the Senate?', options: ['Voting member', 'Presiding officer', 'Speaker', 'Committee chair'], answer: 'Presiding officer' },
  { q: 'What is the term for a system where power is divided between national and state governments?', options: ['Unitary system', 'Federal system', 'Confederation', 'Centralized system'], answer: 'Federal system' },
  { q: 'What is the process called when citizens can remove an official from office?', options: ['Impeachment', 'Recall', 'Censure', 'Expulsion'], answer: 'Recall' },
  { q: 'What is the term for freedom from government control?', options: ['Liberty', 'Justice', 'Equality', 'Fraternity'], answer: 'Liberty' },

  // Additional General Knowledge (20 questions)
  { q: 'What is the most spoken language in the world?', options: ['English', 'Mandarin Chinese', 'Spanish', 'Hindi'], answer: 'Mandarin Chinese' },
  { q: 'What is the currency of Japan?', options: ['Yuan', 'Won', 'Yen', 'Ringgit'], answer: 'Yen' },
  { q: 'What is the currency of the European Union?', options: ['Dollar', 'Pound', 'Euro', 'Franc'], answer: 'Euro' },
  { q: 'What is the longest river in Asia?', options: ['Ganges', 'Yangtze', 'Mekong', 'Indus'], answer: 'Yangtze' },
  { q: 'What is the currency of South Korea?', options: ['Yen', 'Won', 'Yuan', 'Ringgit'], answer: 'Won' },
  { q: 'What is the largest desert in Asia?', options: ['Gobi', 'Thar', 'Karakum', 'Taklamakan'], answer: 'Gobi' },
  { q: 'What is the highest mountain in Europe?', options: ['Mont Blanc', 'Matterhorn', 'Elbrus', 'Mont Blanc'], answer: 'Elbrus' },
  { q: 'What is the currency of Russia?', options: ['Ruble', 'Euro', 'Dollar', 'Pound'], answer: 'Ruble' },
  { q: 'What is the largest lake in Africa?', options: ['Lake Victoria', 'Lake Tanganyika', 'Lake Malawi', 'Lake Chad'], answer: 'Lake Victoria' },
  { q: 'What is the currency of Nigeria?', options: ['Naira', 'Cedi', 'Shilling', 'Rand'], answer: 'Naira' },
  { q: 'What is the longest river in South America?', options: ['Amazon', 'Orinoco', 'Paraná', 'Magdalena'], answer: 'Amazon' },
  { q: 'What is the currency of Brazil?', options: ['Peso', 'Real', 'Dollar', 'Euro'], answer: 'Real' },
  { q: 'What is the largest island in the Mediterranean?', options: ['Sicily', 'Sardinia', 'Cyprus', 'Crete'], answer: 'Sicily' },
  { q: 'What is the currency of Turkey?', options: ['Lira', 'Dinar', 'Riyal', 'Dirham'], answer: 'Lira' },
  { q: 'What is the most populous city in the world?', options: ['Tokyo', 'Delhi', 'Shanghai', 'São Paulo'], answer: 'Tokyo' },
  { q: 'What is the currency of Saudi Arabia?', options: ['Dinar', 'Riyal', 'Dirham', 'Rial'], answer: 'Riyal' },
  { q: 'What is the largest rainforest in the world?', options: ['Amazon', 'Congo', 'Daintree', 'Monteverde'], answer: 'Amazon' },
  { q: 'What is the currency of Mexico?', options: ['Peso', 'Real', 'Dollar', 'Euro'], answer: 'Peso' },
  { q: 'What is the largest coral formation?', options: ['Great Barrier Reef', 'Belize Barrier Reef', 'Red Sea Coral Reef', 'New Caledonia Barrier Reef'], answer: 'Great Barrier Reef' },
  { q: 'What is the currency of Australia?', options: ['Dollar', 'Pound', 'Euro', 'Rand'], answer: 'Dollar' },
];
'''

# Split content into parts
lines = content.split('\n')
part1 = '\n'.join(lines[:92])  # Everything before line 93

# Reconstruct the file
new_content = part1 + '\n' + new_array + '\n'

# Write back
with open('ChatGamesModal.jsx', 'w', encoding='utf-8') as f:
    f.write(new_content)

print('File updated successfully')
