import { PageContainer } from '../../components/layout/LayoutWrappers';
import { PageHeader } from '../../components/ui/UIElements';
import { Compass, Sparkles, CheckCircle2, Circle } from 'lucide-react';
import { Card, CardContent } from '../../components/ui/Card';

const paths = [
  {
    id: '1',
    title: 'Senior AI Architect Track',
    description: 'Generated based on your goal to lead Project Phoenix and your current mastery in Python & Neural Nets.',
    progress: 35,
    steps: [
      { name: 'Course: Advanced AI', completed: true },
      { name: 'Read: Scaling ML Pipelines', completed: false },
      { name: 'Mentorship: System Design with Chief AI Officer', completed: false },
    ]
  }
];

export default function LearningPaths() {
  return (
    <PageContainer>
      <PageHeader
        title="AI Learning Paths"
        description="Personalized journeys generated by AI to help you achieve your career and project goals."
        action={
          <div className="flex gap-2">
            <button className="bg-purple-500 text-white px-4 py-2 rounded-lg font-bold text-sm hover:bg-purple-600 transition-colors shadow-[0_0_15px_rgba(168,85,247,0.3)] flex items-center gap-2">
               <Sparkles className="w-4 h-4" /> Generate New Path
            </button>
          </div>
        }
      />
      
      <div className="space-y-6 max-w-4xl mx-auto">
        {paths.map(path => (
          <Card key={path.id} className="border-border bg-surface/50 hover:border-accent transition-all relative overflow-hidden">
             {/* Progress background visual */}
             <div className="absolute top-0 left-0 h-1 bg-accent transition-all" style={{ width: `${path.progress}%` }}></div>
             
             <CardContent className="p-8">
               <div className="flex items-start gap-4 mb-6">
                  <div className="w-12 h-12 rounded-xl bg-accent/20 flex items-center justify-center shrink-0">
                     <Compass className="w-6 h-6 text-accent" />
                  </div>
                  <div>
                     <h2 className="text-2xl font-bold text-white mb-2">{path.title}</h2>
                     <p className="text-sm text-text-muted leading-relaxed">{path.description}</p>
                  </div>
               </div>

               <div className="space-y-4">
                  <h4 className="text-sm font-bold text-white uppercase tracking-wider mb-2">Milestones</h4>
                  {path.steps.map((step, idx) => (
                     <div key={idx} className="flex items-center gap-3 p-3 rounded-lg border border-border/50 bg-white/5 hover:bg-white/10 transition-colors">
                        {step.completed ? (
                           <CheckCircle2 className="w-5 h-5 text-accent shrink-0" />
                        ) : (
                           <Circle className="w-5 h-5 text-text-muted shrink-0" />
                        )}
                        <span className={`text-sm ${step.completed ? 'text-white' : 'text-text-muted'}`}>{step.name}</span>
                        {step.completed && <span className="ml-auto text-xs text-accent font-bold">Done</span>}
                     </div>
                  ))}
               </div>
             </CardContent>
          </Card>
        ))}
      </div>
    </PageContainer>
  );
}
