export const DEFAULT_ACHIEVEMENTS = [
  {
    id: 'first_task',
    title: 'First Mission Complete',
    description: 'Completed and received approval for the first BeastBuck task.',
    rewardXP: 50,
    badge: 'Leader',
  },
  {
    id: 'task_streak_5',
    title: 'Mission Builder',
    description: 'Completed five approved tasks.',
    rewardXP: 150,
    badge: 'Leader',
  },
  {
    id: 'first_experiment',
    title: 'First Experiment',
    description: 'Published or completed a science experiment.',
    rewardXP: 100,
    badge: 'Scientist',
  },
  {
    id: 'product_creator',
    title: 'Product Creator',
    description: 'Created a product for the BeastBuck marketplace.',
    rewardXP: 100,
    badge: 'Inventor',
  },
  {
    id: 'coding_helper',
    title: 'Coding Helper',
    description: 'Contributed useful coding work or developer help.',
    rewardXP: 120,
    badge: 'Developer',
  },
  {
    id: 'team_contributor',
    title: 'Team Contributor',
    description: 'Helped a team project move forward.',
    rewardXP: 100,
    badge: 'Leader',
  },
  { id: 'top_innovator', title: 'Top Innovator', description: 'Recognized for top innovation.', rewardXP: 1000, badge: 'Innovator' },
  { id: 'top_researcher', title: 'Top Researcher', description: 'Recognized for top research.', rewardXP: 1000, badge: 'Scientist' },
  { id: 'top_builder', title: 'Top Builder', description: 'Recognized for building great products.', rewardXP: 1000, badge: 'Builder' },
  { id: 'top_collaborator', title: 'Top Collaborator', description: 'Recognized for excellent collaboration.', rewardXP: 800, badge: 'Leader' },
  { id: 'top_leader', title: 'Top Leader', description: 'Recognized for leadership.', rewardXP: 1000, badge: 'Leader' },
  { id: 'top_educator', title: 'Top Educator', description: 'Recognized for top education.', rewardXP: 1000, badge: 'Educator' },
  { id: 'top_scientist', title: 'Top Scientist', description: 'Recognized for top science.', rewardXP: 1000, badge: 'Scientist' },
  { id: 'community_legend', title: 'Community Legend', description: 'A legend of the BeastBuck community.', rewardXP: 2000, badge: 'Leader' },
  { id: 'top_mentor', title: 'Top Mentor', description: 'Top mentorship.', rewardXP: 1000, badge: 'Educator' },
  { id: 'top_knowledge_contributor', title: 'Top Knowledge Contributor', description: 'Contributed heavily to knowledge.', rewardXP: 800, badge: 'Educator' },
  { id: 'top_problem_solver', title: 'Top Problem Solver', description: 'Solved major problems.', rewardXP: 800, badge: 'Developer' },
  { id: 'community_helper', title: 'Community Helper', description: 'Helped the community.', rewardXP: 500, badge: 'Leader' },
  { id: 'top_founder', title: 'Top Founder', description: 'Exceptional venture founder.', rewardXP: 1500, badge: 'Founder' },
  { id: 'top_entrepreneur', title: 'Top Entrepreneur', description: 'Leading entrepreneur in the ecosystem.', rewardXP: 1500, badge: 'Entrepreneur' },
  { id: 'top_venture_builder', title: 'Top Venture Builder', description: 'Master of building ventures.', rewardXP: 1200, badge: 'Builder' },
  { id: 'top_startup_leader', title: 'Top Startup Leader', description: 'Led a startup to success.', rewardXP: 1200, badge: 'Leader' },
  { id: 'top_business_strategist', title: 'Top Business Strategist', description: 'Exceptional business strategy.', rewardXP: 1000, badge: 'Strategist' },
  { id: 'top_growth_leader', title: 'Top Growth Leader', description: 'Drove massive venture growth.', rewardXP: 1200, badge: 'Leader' },
  { id: 'top_venture_team', title: 'Top Venture Team', description: 'Part of an elite venture team.', rewardXP: 1000, badge: 'Team' },
  { id: 'top_learner', title: 'Top Learner', description: 'Outstanding learner in the Academy.', rewardXP: 800, badge: 'Learner' },
  { id: 'top_instructor', title: 'Top Instructor', description: 'Exceptional course instructor.', rewardXP: 1200, badge: 'Educator' },
  { id: 'top_research_student', title: 'Top Research Student', description: 'Excelled in research-based learning.', rewardXP: 1000, badge: 'Scientist' },
  { id: 'top_certification_earner', title: 'Top Certification Earner', description: 'Earned the most certifications.', rewardXP: 1000, badge: 'Educator' },
  { id: 'top_specialization_expert', title: 'Top Specialization Expert', description: 'Completed multiple specializations.', rewardXP: 1200, badge: 'Expert' },
  // --- Governance & Trust OS (Step 34) ---
  { id: 'most_trusted_member', title: 'Most Trusted Member', description: 'Achieved Elite Trust level through consistent integrity.', rewardXP: 2000, badge: 'Trust' },
  { id: 'community_champion', title: 'Community Champion', description: 'Top contributor to governance proposals and community decisions.', rewardXP: 1500, badge: 'Leader' },
  { id: 'governance_contributor', title: 'Governance Contributor', description: 'Actively participated in 20+ governance votes.', rewardXP: 800, badge: 'Governance' },
  { id: 'top_reviewer', title: 'Top Reviewer', description: 'Provided the most helpful peer reviews and endorsements.', rewardXP: 1000, badge: 'Reviewer' },
  { id: 'best_collaborator', title: 'Best Collaborator', description: 'Recognized for outstanding cross-team collaboration.', rewardXP: 1000, badge: 'Team' },
  { id: 'most_helpful_member', title: 'Most Helpful Member', description: 'Consistently helped others across the ecosystem.', rewardXP: 1200, badge: 'Leader' },
  { id: 'trust_ambassador', title: 'Trust Ambassador', description: 'Maintained Platinum or Elite Trust for 6+ months.', rewardXP: 1500, badge: 'Trust' },
  { id: 'leadership_excellence', title: 'Leadership Excellence', description: 'Won or served in a community leadership election.', rewardXP: 2000, badge: 'Leader' },
  // --- Intelligence & Predictive AI OS (Step 35) ---
  { id: 'top_strategist', title: 'Top Strategist', description: 'Successfully navigated complex ecosystem challenges using AI insights.', rewardXP: 1800, badge: 'Strategist' },
  { id: 'top_analyst', title: 'Top Analyst', description: 'Contributed vital analytics to the ecosystem intelligence network.', rewardXP: 1500, badge: 'Scientist' },
  { id: 'top_ecosystem_builder', title: 'Top Ecosystem Builder', description: 'Fostered high-growth cross-department collaborations.', rewardXP: 2000, badge: 'Builder' },
  { id: 'intelligence_contributor', title: 'Intelligence Contributor', description: 'Regularly engaged with AI forecasting and trend analysis tools.', rewardXP: 800, badge: 'Explorer' },
  { id: 'growth_architect', title: 'Growth Architect', description: 'Designed scalable processes adopted ecosystem-wide.', rewardXP: 1800, badge: 'Innovator' },
  { id: 'opportunity_creator', title: 'Opportunity Creator', description: 'Generated significant new opportunities for the BeastBuck community.', rewardXP: 1500, badge: 'Leader' },
  // --- Ecosystem & Legacy OS (Step 36) ---
  { id: 'global_ambassador', title: 'Global Ambassador', description: 'Represented BeastBuck on a global stage.', rewardXP: 2500, badge: 'Leader' },
  { id: 'community_builder', title: 'Community Builder', description: 'Built and led a thriving local chapter.', rewardXP: 1500, badge: 'Builder' },
  { id: 'legacy_contributor', title: 'Legacy Contributor', description: 'Made a historic contribution preserved in the Legacy Registry.', rewardXP: 5000, badge: 'Legend' },
  { id: 'ecosystem_architect', title: 'Ecosystem Architect', description: 'Forged key institutional partnerships.', rewardXP: 2000, badge: 'Strategist' },
  { id: 'global_leader', title: 'Global Leader', description: 'Achieved top 10 status in Global Rankings.', rewardXP: 3000, badge: 'Leader' },
  { id: 'impact_creator', title: 'Impact Creator', description: 'Generated exceptional impact scores across multiple disciplines.', rewardXP: 2000, badge: 'Innovator' },
];

export function getAchievementById(id) {
  return DEFAULT_ACHIEVEMENTS.find(achievement => achievement.id === id);
}
