import { PageContainer } from '../../components/layout/LayoutWrappers';
import { PageHeader } from '../../components/ui/UIElements';
import { ShieldAlert, Info, AlertTriangle, XCircle } from 'lucide-react';
import { cn } from '../../lib/utils';

export default function IntelligenceAlerts() {
  const alerts = [
    { type: 'CRITICAL', msg: 'Quantum Research Lab activity dropped by 80% this week.', source: 'Research OS' },
    { type: 'HIGH', msg: 'Top creator @jane_doe is showing signs of burnout (reduced login frequency).', source: 'Marketplace' },
    { type: 'MEDIUM', msg: 'New opportunity: Rapid growth in Web3 course enrollments.', source: 'Academy' },
    { type: 'LOW', msg: 'Routine security scan completed.', source: 'System' }
  ];

  const getIcon = (type) => {
    switch(type) {
      case 'CRITICAL': return <XCircle className="w-5 h-5 text-red-500" />;
      case 'HIGH': return <AlertTriangle className="w-5 h-5 text-orange-500" />;
      case 'MEDIUM': return <ShieldAlert className="w-5 h-5 text-yellow-500" />;
      default: return <Info className="w-5 h-5 text-blue-500" />;
    }
  };

  const getBg = (type) => {
    switch(type) {
      case 'CRITICAL': return 'bg-red-500/10 border-red-500/30';
      case 'HIGH': return 'bg-orange-500/10 border-orange-500/30';
      case 'MEDIUM': return 'bg-yellow-500/10 border-yellow-500/30';
      default: return 'bg-blue-500/10 border-blue-500/30';
    }
  };

  return (
    <PageContainer>
      <PageHeader
        title="Intelligence Alerts"
        description="Real-time strategic alerts and warnings generated by the Intelligence Network."
      />

      <div className="flex flex-col gap-3">
        {alerts.map((alert, i) => (
          <div key={i} className={cn("flex items-start gap-4 p-4 rounded-xl border", getBg(alert.type))}>
            <div className="mt-0.5">{getIcon(alert.type)}</div>
            <div>
              <div className="flex items-center gap-2 mb-1">
                <span className={cn("text-xs font-bold uppercase tracking-widest", alert.type === 'CRITICAL' ? 'text-red-400' : 'text-text-muted')}>
                  {alert.type} PRIORITY
                </span>
                <span className="text-xs text-text-muted border-l border-border pl-2">{alert.source}</span>
              </div>
              <p className="text-sm font-medium text-white">{alert.msg}</p>
            </div>
            <button className="ml-auto text-xs font-bold text-accent hover:underline">Acknowledge</button>
          </div>
        ))}
      </div>
    </PageContainer>
  );
}
